apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-metrics
  annotations:
    trait.camel.apache.org/prometheus.enabled: "true"
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: ephemeral-kafka-source
    properties:
      bootstrapServers: my-cluster-kafka-bootstrap.metrics.svc:9092
      topic: metrics
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: metrics-bridge